from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from hitep.openapi_server.models.base_model import Model
from hitep.openapi_server import util


class Model3DCoordinate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, x=None, y=None, z=None):  # noqa: E501
        """Model3DCoordinate - a model defined in OpenAPI

        :param x: The x of this Model3DCoordinate.  # noqa: E501
        :type x: float
        :param y: The y of this Model3DCoordinate.  # noqa: E501
        :type y: float
        :param z: The z of this Model3DCoordinate.  # noqa: E501
        :type z: float
        """
        self.openapi_types = {
            'x': float,
            'y': float,
            'z': float
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y',
            'z': 'z'
        }

        self._x = x
        self._y = y
        self._z = z

    @classmethod
    def from_dict(cls, dikt) -> 'Model3DCoordinate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The 3DCoordinate of this Model3DCoordinate.  # noqa: E501
        :rtype: Model3DCoordinate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> float:
        """Gets the x of this Model3DCoordinate.


        :return: The x of this Model3DCoordinate.
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x: float):
        """Sets the x of this Model3DCoordinate.


        :param x: The x of this Model3DCoordinate.
        :type x: float
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self) -> float:
        """Gets the y of this Model3DCoordinate.


        :return: The y of this Model3DCoordinate.
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y: float):
        """Sets the y of this Model3DCoordinate.


        :param y: The y of this Model3DCoordinate.
        :type y: float
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y

    @property
    def z(self) -> float:
        """Gets the z of this Model3DCoordinate.


        :return: The z of this Model3DCoordinate.
        :rtype: float
        """
        return self._z

    @z.setter
    def z(self, z: float):
        """Sets the z of this Model3DCoordinate.


        :param z: The z of this Model3DCoordinate.
        :type z: float
        """
        if z is None:
            raise ValueError("Invalid value for `z`, must not be `None`")  # noqa: E501

        self._z = z
