from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from hitep.openapi_server.models.base_model import Model
from hitep.openapi_server import util


class StopScenarioRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, end=None):  # noqa: E501
        """StopScenarioRequest - a model defined in OpenAPI

        :param end: The end of this StopScenarioRequest.  # noqa: E501
        :type end: datetime
        """
        self.openapi_types = {
            'end': datetime
        }

        self.attribute_map = {
            'end': 'end'
        }

        self._end = end

    @classmethod
    def from_dict(cls, dikt) -> 'StopScenarioRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The stopScenario_request of this StopScenarioRequest.  # noqa: E501
        :rtype: StopScenarioRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def end(self) -> datetime:
        """Gets the end of this StopScenarioRequest.

        End date of the session  # noqa: E501

        :return: The end of this StopScenarioRequest.
        :rtype: datetime
        """
        return self._end

    @end.setter
    def end(self, end: datetime):
        """Sets the end of this StopScenarioRequest.

        End date of the session  # noqa: E501

        :param end: The end of this StopScenarioRequest.
        :type end: datetime
        """

        self._end = end
