from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi.models.base_model import Model
from openapi import util


class Coordinate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, x=None, y=None):  # noqa: E501
        """Coordinate - a model defined in OpenAPI

        :param x: The x of this Coordinate.  # noqa: E501
        :type x: float
        :param y: The y of this Coordinate.  # noqa: E501
        :type y: float
        """
        self.openapi_types = {
            'x': float,
            'y': float
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y'
        }

        self._x = x
        self._y = y

    @classmethod
    def from_dict(cls, dikt) -> 'Coordinate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Coordinate of this Coordinate.  # noqa: E501
        :rtype: Coordinate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> float:
        """Gets the x of this Coordinate.


        :return: The x of this Coordinate.
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x: float):
        """Sets the x of this Coordinate.


        :param x: The x of this Coordinate.
        :type x: float
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self) -> float:
        """Gets the y of this Coordinate.


        :return: The y of this Coordinate.
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y: float):
        """Sets the y of this Coordinate.


        :param y: The y of this Coordinate.
        :type y: float
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y
