from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi.models.base_model import Model
from openapi import util


class GetScenario200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, location=None, user=None):  # noqa: E501
        """GetScenario200Response - a model defined in OpenAPI

        :param location: The location of this GetScenario200Response.  # noqa: E501
        :type location: str
        :param user: The user of this GetScenario200Response.  # noqa: E501
        :type user: str
        """
        self.openapi_types = {
            'location': str,
            'user': str
        }

        self.attribute_map = {
            'location': 'location',
            'user': 'user'
        }

        self._location = location
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'GetScenario200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getScenario_200_response of this GetScenario200Response.  # noqa: E501
        :rtype: GetScenario200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def location(self) -> str:
        """Gets the location of this GetScenario200Response.

        IRI of the location.  # noqa: E501

        :return: The location of this GetScenario200Response.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this GetScenario200Response.

        IRI of the location.  # noqa: E501

        :param location: The location of this GetScenario200Response.
        :type location: str
        """

        self._location = location

    @property
    def user(self) -> str:
        """Gets the user of this GetScenario200Response.

        IRI identifying the user  # noqa: E501

        :return: The user of this GetScenario200Response.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this GetScenario200Response.

        IRI identifying the user  # noqa: E501

        :param user: The user of this GetScenario200Response.
        :type user: str
        """

        self._user = user
