from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi.models.base_model import Model
from openapi.models.bounding_box import BoundingBox
from openapi import util

from openapi.models.bounding_box import BoundingBox  # noqa: E501

class SubmitGazeRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, paintaing=None, entity=None, bounding_box=None):  # noqa: E501
        """SubmitGazeRequest - a model defined in OpenAPI

        :param paintaing: The paintaing of this SubmitGazeRequest.  # noqa: E501
        :type paintaing: str
        :param entity: The entity of this SubmitGazeRequest.  # noqa: E501
        :type entity: List[str]
        :param bounding_box: The bounding_box of this SubmitGazeRequest.  # noqa: E501
        :type bounding_box: BoundingBox
        """
        self.openapi_types = {
            'paintaing': str,
            'entity': List[str],
            'bounding_box': BoundingBox
        }

        self.attribute_map = {
            'paintaing': 'paintaing',
            'entity': 'entity',
            'bounding_box': 'boundingBox'
        }

        self._paintaing = paintaing
        self._entity = entity
        self._bounding_box = bounding_box

    @classmethod
    def from_dict(cls, dikt) -> 'SubmitGazeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The submitGaze_request of this SubmitGazeRequest.  # noqa: E501
        :rtype: SubmitGazeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def paintaing(self) -> str:
        """Gets the paintaing of this SubmitGazeRequest.

        IRI of the painting that is the target of the user gaze  # noqa: E501

        :return: The paintaing of this SubmitGazeRequest.
        :rtype: str
        """
        return self._paintaing

    @paintaing.setter
    def paintaing(self, paintaing: str):
        """Sets the paintaing of this SubmitGazeRequest.

        IRI of the painting that is the target of the user gaze  # noqa: E501

        :param paintaing: The paintaing of this SubmitGazeRequest.
        :type paintaing: str
        """

        self._paintaing = paintaing

    @property
    def entity(self) -> List[str]:
        """Gets the entity of this SubmitGazeRequest.

        IRIs of the entities that are target of the user gaze  # noqa: E501

        :return: The entity of this SubmitGazeRequest.
        :rtype: List[str]
        """
        return self._entity

    @entity.setter
    def entity(self, entity: List[str]):
        """Sets the entity of this SubmitGazeRequest.

        IRIs of the entities that are target of the user gaze  # noqa: E501

        :param entity: The entity of this SubmitGazeRequest.
        :type entity: List[str]
        """

        self._entity = entity

    @property
    def bounding_box(self) -> BoundingBox:
        """Gets the bounding_box of this SubmitGazeRequest.


        :return: The bounding_box of this SubmitGazeRequest.
        :rtype: BoundingBox
        """
        return self._bounding_box

    @bounding_box.setter
    def bounding_box(self, bounding_box: BoundingBox):
        """Sets the bounding_box of this SubmitGazeRequest.


        :param bounding_box: The bounding_box of this SubmitGazeRequest.
        :type bounding_box: BoundingBox
        """

        self._bounding_box = bounding_box
